import { BookOutlined, PlusOutlined, ShareAltOutlined } from '@ant-design/icons'
import { Button, Col, Row, Space, Tag, Typography } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <Row justify="center">
      <Head>
        <title>CookBook App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Col span={16}>
        <Row>
          <Col
            span={12}
            style={{
              height: '60vh',
              background: 'rgba(40,44,44)',
              color: '#fff',
              padding: '15px',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'space-between',
            }}
          >
            <Row>
              <Tag>COOKBOOK</Tag>
            </Row>
            <Space direction="vertical" size="large">
              <Space>
                <BookOutlined />
                <Typography.Text style={{ color: '#fff' }}>
                  Create your cookbook
                </Typography.Text>
              </Space>
              <Space>
                <PlusOutlined />
                <Typography.Text style={{ color: '#fff' }}>
                  Add your recipes
                </Typography.Text>
              </Space>
              <Space>
                <ShareAltOutlined />
                <Typography.Text style={{ color: '#fff' }}>
                  Share it with your friends
                </Typography.Text>
              </Space>
            </Space>
            <Row justify="end">
              <Button onClick={() => router.push('/cookbook')}>Create</Button>
            </Row>
          </Col>
          <Col
            span={12}
            style={{
              height: '60vh',
              background: 'rgb(226,215,215)',
              color: '#fff',
              padding: '15px',
            }}
          >
            <Tag onClick={() => router.push('recipe')}>RECIPES</Tag>
          </Col>
        </Row>
      </Col>
    </Row>
  )
}

export default Home
